### ISSUE TITLE
Build with PG 9.6.1 on FreeBSD

### ISSUE THREAD

**Issue by alexandervasylev** [plproxy/plproxy#25]
Hello.

I tried install plproxy on FreeBSD 10.3-RELEASE and PostgreSQL 9.6.2 and got some errors. Anyone can help solve this?

```
git clone https://github.com/plproxy/plproxy
git checkout master
gmake PG_CONFIG=/usr/local/pgsql-9.6/bin/pg_config

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -DPIC -I/usr/local/pgsql-9.6/include/server -I/usr/local/pgsql-9.6/include -DNO_SELECT=0 -I. -I./ -I/usr/local/pgsql-9.6/include/server -I/usr/local/pgsql-9.6/include/internal   -c -o src/execute.o src/execute.c
src/execute.c: In function 'socket_set_keepalive':
src/execute.c:287:3: warning: implicit declaration of function 'setsockopt' [-Wimplicit-function-declaration]
   res = setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &val, sizeof(val));
   ^
src/execute.c:287:24: error: 'SOL_SOCKET' undeclared (first use in this function)
   res = setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &val, sizeof(val));
                        ^
src/execute.c:287:24: note: each undeclared identifier is reported only once for each function it appears in
src/execute.c:287:36: error: 'SO_KEEPALIVE' undeclared (first use in this function)
   res = setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &val, sizeof(val));
                                    ^
src/execute.c: In function 'setup_keepalive':
src/execute.c:353:18: error: storage size of 'sa' isn't known
  struct sockaddr sa;
                  ^
src/execute.c:354:12: warning: unused variable 'salen' [-Wunused-variable]
  socklen_t salen = sizeof(sa);
            ^
src/execute.c:353:18: warning: unused variable 'sa' [-Wunused-variable]
  struct sockaddr sa;
                  ^
gmake: *** [<builtin>: src/execute.o] Error 1
```

**Comment by alexandervasylev** [comment]
Thanks. I will try.
